spring.application.name=PI
spring.datasource.url=jdbc:postgresql://localhost:5433/b2u_hub
spring.datasource.username=postgres
spring.datasource.password=1312

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081
cloudinary.cloud_name=die3g00yu
cloudinary.api_key=484237194643237
cloudinary.api_secret=VnE1naZJFFUj-Inx2CtwIOZhQdI

# LINKEDIN OAUTH2

spring.security.oauth2.client.registration.linkedin.client-id=77viq2gtvtba2t

spring.security.oauth2.client.registration.linkedin.client-secret=WPL_AP1.snQrTGac9lh2DfIB.0s5XMg==

spring.security.oauth2.client.registration.linkedin.scope=openid,profile,email

spring.security.oauth2.client.registration.linkedin.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.linkedin.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.linkedin.client-name=LinkedIn

spring.security.oauth2.client.provider.linkedin.authorization-uri=https://www.linkedin.com/oauth/v2/authorization
spring.security.oauth2.client.provider.linkedin.token-uri=https://www.linkedin.com/oauth/v2/accessToken
spring.security.oauth2.client.provider.linkedin.user-info-uri=https://api.linkedin.com/v2/userinfo
spring.security.oauth2.client.provider.linkedin.user-name-attribute=sub
app.frontend-url=http://localhost:4200