const express=require('express');const cors=require('cors');const helmet=require('helmet');const morgan=require('morgan');const fs=require('fs');const path=require('path');const {v4:uuid}=require('uuid');
const app=express();app.use(cors({origin:'http://localhost:4200'}));app.use(helmet());app.use(morgan('dev'));app.use(express.json());
const file=path.join(__dirname,'data','db.json');
function read(){if(!fs.existsSync(file))fs.writeFileSync(file,JSON.stringify(seed(),null,2));return JSON.parse(fs.readFileSync(file,'utf8'))}
function write(db){fs.writeFileSync(file,JSON.stringify(db,null,2))}
function seed(){return {missions:[{id:uuid(),title:'Application de gestion RH',description:'Développer un module RH avec dashboard, rôles, workflow et reporting.',budget:1800,skills:['Angular','Node.js','MongoDB','Dashboard'],status:'open',ownerEmail:'client1@mail.com',demoUrl:'',comments:[{author:'admin',text:'Mission prioritaire'}]},{id:uuid(),title:'Site vitrine freelance',description:'Créer un front office public responsive avec espace admin et publication de missions.',budget:900,skills:['Angular','UI','CSS','SEO'],status:'open',ownerEmail:'client2@mail.com',comments:[]}],developers:[{id:uuid(),name:'Malek',email:'malek@mail.com',skills:['Angular','Node.js','MongoDB','QlikView','Dashboard'],level:'mid',rate:120,availability:'available',permissions:['apply','demo','comment']},{id:uuid(),name:'Sarra',email:'sarra@mail.com',skills:['UI','CSS','Angular','SEO'],level:'senior',rate:180,availability:'available',permissions:['apply','demo','comment']},{id:uuid(),name:'Ahmed',email:'ahmed@mail.com',skills:['Python','AI','Matching','API'],level:'senior',rate:220,availability:'busy',permissions:['apply','demo','comment']}],assignments:[]}}
const tokens=s=>String(s||'').toLowerCase().replace(/[^a-z0-9à-ÿ ]/gi,' ').split(/\s+/).filter(w=>w.length>2);
const cosine=(a,b)=>{const A=tokens(a),B=tokens(b),all=[...new Set([...A,...B])];let dot=0,na=0,nb=0;for(const w of all){const x=A.filter(v=>v===w).length,y=B.filter(v=>v===w).length;dot+=x*y;na+=x*x;nb+=y*y}return na&&nb?dot/(Math.sqrt(na)*Math.sqrt(nb)):0};
function matchScore(m,d){const ms=m.skills.map(x=>x.toLowerCase()),ds=d.skills.map(x=>x.toLowerCase());const common=ms.filter(s=>ds.includes(s));const skill=ms.length?common.length/ms.length:0;const text=cosine(m.description+' '+m.title,d.skills.join(' '));const avail=d.availability==='available'?1:.35;const level={junior:.55,mid:.78,senior:1}[d.level]||.6;const budget=m.budget>=d.rate*5?1:m.budget>=d.rate*3?.75:.45;const score=Math.round((skill*.45+text*.2+avail*.15+level*.1+budget*.1)*100);const reasons=[];if(common.length)reasons.push('Compétences communes: '+common.join(', '));reasons.push('Disponibilité: '+d.availability);reasons.push('Niveau: '+d.level);reasons.push('Compatibilité budget');return {developer:d,score,reasons,explanation:`Score calculé par compétences, similarité textuelle, disponibilité, niveau et budget.`}}
app.get('/api/health',(req,res)=>res.json({ok:true}));
app.get('/api/missions',(req,res)=>res.json(read().missions));
app.post('/api/missions',(req,res)=>{const db=read();const m={id:uuid(),title:req.body.title,description:req.body.description,budget:+req.body.budget||0,skills:req.body.skills||[],status:'open',ownerEmail:req.body.ownerEmail,demoUrl:req.body.demoUrl||'',comments:[]};db.missions.unshift(m);write(db);res.status(201).json(m)});
app.put('/api/missions/:id',(req,res)=>{const db=read();const i=db.missions.findIndex(m=>m.id===req.params.id);if(i<0)return res.status(404).json({message:'Mission introuvable'});db.missions[i]={...db.missions[i],...req.body,id:req.params.id};write(db);res.json(db.missions[i])});
app.delete('/api/missions/:id',(req,res)=>{const db=read();const m=db.missions.find(x=>x.id===req.params.id);if(!m)return res.status(404).json({message:'Mission introuvable'});const email=req.query.email;if(email!==m.ownerEmail && email!=='admin@system.local')return res.status(403).json({message:'Suppression refusée: seul le créateur ou admin peut supprimer'});db.missions=db.missions.filter(x=>x.id!==req.params.id);write(db);res.json({ok:true})});
app.post('/api/missions/:id/comments',(req,res)=>{const db=read();const m=db.missions.find(x=>x.id===req.params.id);if(!m)return res.status(404).json({message:'Mission introuvable'});m.comments=m.comments||[];m.comments.push({author:req.body.author||'public',text:req.body.text||'',date:new Date().toISOString()});write(db);res.json(m)});
app.post('/api/missions/:id/assign',(req,res)=>{const db=read();db.assignments.push({id:uuid(),missionId:req.params.id,developerId:req.body.developerId,date:new Date().toISOString()});const m=db.missions.find(x=>x.id===req.params.id);if(m)m.status='assigned';write(db);res.json({ok:true})});
app.get('/api/developers',(req,res)=>res.json(read().developers));
app.post('/api/developers',(req,res)=>{const db=read();const d={id:uuid(),name:req.body.name,email:req.body.email,skills:req.body.skills||[],level:req.body.level||'junior',rate:+req.body.rate||0,availability:req.body.availability||'available',permissions:['apply','demo','comment']};db.developers.unshift(d);write(db);res.status(201).json(d)});
app.get('/api/ai/match/:missionId',(req,res)=>{const db=read();const m=db.missions.find(x=>x.id===req.params.missionId);if(!m)return res.status(404).json({message:'Mission introuvable'});res.json(db.developers.map(d=>matchScore(m,d)).sort((a,b)=>b.score-a.score))});
app.get('/api/stats',(req,res)=>{const db=read();res.json({missions:db.missions.length,developers:db.developers.length,budget:db.missions.reduce((s,m)=>s+(+m.budget||0),0),open:db.missions.filter(m=>m.status==='open').length})});
app.listen(3000,()=>console.log('API Gestion Missions prête: http://localhost:3000/api'));
