import { bootstrapApplication } from '@angular/platform-browser';
import { Component, Injectable } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Routes, RouterLink, RouterOutlet, Router, provideRouter } from '@angular/router';
import { HttpClient, provideHttpClient } from '@angular/common/http';
const API='http://localhost:3000/api';
type Mission={id:string;title:string;description:string;budget:number;skills:string[];status:string;ownerEmail:string;demoUrl?:string;comments?:any[]};
type Dev={id:string;name:string;email:string;skills:string[];level:string;rate:number;availability:string;permissions?:string[]};
@Injectable({providedIn:'root'}) class Api{constructor(private http:HttpClient){} missions(){return this.http.get<Mission[]>(API+'/missions')} addMission(m:any){return this.http.post<Mission>(API+'/missions',m)} updateMission(id:string,m:any){return this.http.put<Mission>(API+'/missions/'+id,m)} deleteMission(id:string,email:string){return this.http.delete(API+`/missions/${id}?email=${encodeURIComponent(email)}`)} comment(id:string,c:any){return this.http.post(API+'/missions/'+id+'/comments',c)} devs(){return this.http.get<Dev[]>(API+'/developers')} addDev(d:any){return this.http.post<Dev>(API+'/developers',d)} stats(){return this.http.get<any>(API+'/stats')} match(id:string){return this.http.get<any[]>(API+'/ai/match/'+id)} assistant(message:string){return this.http.post<any>(API+'/assistant/chat',{message})}}
@Component({selector:'app-root',standalone:true,imports:[RouterOutlet],template:`<router-outlet/>`}) class Root{}
@Component({standalone:true,imports:[RouterLink,RouterOutlet],template:`<nav class="nav"><a routerLink="/" class="brand">Gestion Missions</a><div class="links"><a routerLink="/missions">Missions</a><a routerLink="/publier">Publier</a><a routerLink="/developers">Développeurs</a><a routerLink="/assistant">Assistant IA</a></div></nav><router-outlet/><footer class="footer">Maquette noir et blanc — plateforme type freelance IT.</footer>`}) class PublicLayout{}
@Component({standalone:true,imports:[RouterLink],template:`<section class="hero"><h1>Plateforme publique de missions IT</h1><p>Un site type freelance: publication de missions, développeurs, budget, commentaires, démos, BackOffice Admin et IA Matching sans API payante.</p><a class="btn" routerLink="/missions">Voir les missions</a> <a class="btn light" routerLink="/assistant">Assistant IA</a></section><section class="grid"><div class="card"><h3>FrontOffice public</h3><p>Le public peut consulter, ajouter et gérer ses propres missions.</p></div><div class="card"><h3>BackOffice Admin</h3><p>Accessible par route /admin pour piloter missions, budget, profils et statistiques.</p></div><div class="card"><h3>IA Matching avancé</h3><p>Score explicable: compétences, budget, disponibilité, niveau et similarité textuelle.</p></div><div class="card"><h3>Assistant IA local</h3><p>Chatbot gratuit pour conseiller, rédiger et expliquer le projet sans clé API.</p></div></section>`}) class Home{}
@Component({standalone:true,imports:[CommonModule,RouterLink],template:`<section class="content"><div class="topline"><h1>Missions disponibles</h1><a class="btn" routerLink="/publier">Ajouter une mission</a></div><div class="grid"><div class="card" *ngFor="let m of missions"><h3>{{m.title}}</h3><p>{{m.description}}</p><p><b>Budget:</b> {{m.budget}} DT</p><span class="tag" *ngFor="let s of m.skills">{{s}}</span><p><b>Statut:</b> {{m.status}}</p><a class="btn light" [routerLink]="['/missions',m.id]">Détails</a></div></div></section>`}) class Missions{missions:Mission[]=[];constructor(api:Api){api.missions().subscribe(x=>this.missions=x)}}
@Component({standalone:true,imports:[CommonModule,FormsModule],template:`<section class="content" *ngIf="m"><h1>{{m.title}}</h1><p>{{m.description}}</p><p><b>Budget:</b> {{m.budget}} DT</p><p><b>Créateur:</b> {{m.ownerEmail}}</p><span class="tag" *ngFor="let s of m.skills">{{s}}</span><hr><h3>Commentaires</h3><div class="card" *ngFor="let c of m.comments"><b>{{c.author}}</b><p>{{c.text}}</p></div><div class="form"><input [(ngModel)]="author" placeholder="Votre email"><textarea [(ngModel)]="text" placeholder="Commentaire"></textarea><button class="btn" (click)="sendComment()">Ajouter commentaire</button></div><hr><h3>Démo</h3><p>{{m.demoUrl||'Aucune démo ajoutée'}}</p><hr><h3>Supprimer ma mission</h3><p class="muted">Autorisé seulement si l’email correspond au créateur.</p><input [(ngModel)]="email" placeholder="Email créateur"><button class="btn" (click)="del()">Supprimer</button></section>`}) class MissionDetail{m?:Mission;email='';author='';text='';id=location.pathname.split('/').pop()!;constructor(private api:Api,private router:Router){this.load()}load(){this.api.missions().subscribe(ms=>this.m=ms.find(x=>x.id===this.id))}sendComment(){this.api.comment(this.id,{author:this.author,text:this.text}).subscribe(()=>this.load())}del(){this.api.deleteMission(this.id,this.email).subscribe(()=>this.router.navigateByUrl('/missions'),e=>alert(e.error?.message||'Suppression refusée'))}}
@Component({standalone:true,imports:[FormsModule],template:`<section class="content"><h1>Publier une mission</h1><div class="form"><input [(ngModel)]="m.title" placeholder="Titre"><textarea [(ngModel)]="m.description" placeholder="Description détaillée"></textarea><input [(ngModel)]="skills" placeholder="Compétences: Angular, Node.js..."><input type="number" [(ngModel)]="m.budget" placeholder="Budget DT"><input [(ngModel)]="m.ownerEmail" placeholder="Votre email"><input [(ngModel)]="m.demoUrl" placeholder="Lien démo optionnel"><button class="btn" (click)="save()">Publier</button></div></section>`}) class Publish{skills='';m:any={title:'',description:'',budget:0,ownerEmail:'',demoUrl:''};constructor(private api:Api,private router:Router){}save(){this.m.skills=this.skills.split(',').map((s:string)=>s.trim()).filter(Boolean);this.api.addMission(this.m).subscribe(()=>this.router.navigateByUrl('/missions'))}}
@Component({standalone:true,imports:[CommonModule,FormsModule],template:`<section class="content"><h1>Développeurs</h1><div class="grid"><div class="card"><h3>Ajouter profil</h3><div class="form"><input [(ngModel)]="d.name" placeholder="Nom"><input [(ngModel)]="d.email" placeholder="Email"><input [(ngModel)]="skills" placeholder="Compétences"><select [(ngModel)]="d.level"><option>junior</option><option>mid</option><option>senior</option></select><input type="number" [(ngModel)]="d.rate" placeholder="TJM / coût"><select [(ngModel)]="d.availability"><option>available</option><option>busy</option></select><button class="btn" (click)="add()">Ajouter</button></div></div><div class="card" *ngFor="let dev of devs"><h3>{{dev.name}}</h3><p>{{dev.email}} — {{dev.level}} — {{dev.availability}}</p><span class="tag" *ngFor="let s of dev.skills">{{s}}</span></div></div></section>`}) class Developers{devs:Dev[]=[];skills='';d:any={level:'junior',availability:'available',rate:0};constructor(private api:Api){this.load()}load(){this.api.devs().subscribe(d=>this.devs=d)}add(){this.d.skills=this.skills.split(',').map((s:string)=>s.trim()).filter(Boolean);this.api.addDev(this.d).subscribe(()=>{this.d={level:'junior',availability:'available',rate:0};this.skills='';this.load()})}}
@Component({standalone:true,imports:[CommonModule,FormsModule],template:`<section class="content"><h1>Assistant IA local</h1><p class="muted">Posez une question sur les missions, budget, compétences, rédaction ou matching. Fonctionne sans API payante.</p><div class="card" style="min-height:280px;max-width:950px"><div *ngFor="let m of messages" [class.black]="m.role==='assistant'" class="card" style="margin-bottom:12px"><b>{{m.role==='user'?'Vous':'Assistant IA'}}</b><p style="white-space:pre-line">{{m.text}}</p></div></div><div class="form" style="max-width:950px;margin-top:16px"><textarea [(ngModel)]="question" placeholder="Exemple: Je suis développeur Angular, quelle mission me convient ?"></textarea><button class="btn" (click)="ask()">Envoyer</button></div><h2>Questions rapides</h2><button class="btn light" (click)="quick('Aide-moi à rédiger une bonne mission Angular avec budget')">Rédiger mission</button> <button class="btn light" (click)="quick('Comment améliorer mon profil développeur ?')">Améliorer profil</button> <button class="btn light" (click)="quick('Explique le matching IA')">Matching IA</button></section>`}) class AssistantAI{question='';messages:any[]=[{role:'assistant',text:'Bonjour, je suis l’assistant IA local de la plateforme. Je peux aider à choisir une mission, rédiger une annonce, expliquer le budget ou conseiller un développeur.'}];constructor(private api:Api){}quick(q:string){this.question=q;this.ask()}ask(){const q=this.question.trim();if(!q)return;this.messages.push({role:'user',text:q});this.question='';this.api.assistant(q).subscribe(r=>this.messages.push({role:'assistant',text:r.reply}),()=>this.messages.push({role:'assistant',text:'Erreur de connexion avec le backend.'}))}}
@Component({standalone:true,imports:[RouterLink,RouterOutlet],template:`<nav class="nav black"><a routerLink="/admin" class="brand">BackOffice Admin</a><div class="links"><a routerLink="/admin">Dashboard</a><a routerLink="/admin/missions">Missions</a><a routerLink="/admin/ai">IA Matching</a><a routerLink="/">FrontOffice</a></div></nav><div class="layout"><aside class="side"><a routerLink="/admin">Dashboard</a><a routerLink="/admin/missions">Gestion missions</a><a routerLink="/admin/developers">Permissions développeurs</a><a routerLink="/admin/ai">Matching IA</a></aside><main><router-outlet/></main></div>`}) class AdminLayout{}
@Component({standalone:true,imports:[CommonModule],template:`<section class="content"><h1>Dashboard Admin</h1><div class="grid"><div class="card"><div class="score">{{s?.missions}}</div><p>Missions</p></div><div class="card"><div class="score">{{s?.developers}}</div><p>Développeurs</p></div><div class="card"><div class="score">{{s?.budget}} DT</div><p>Budget total</p></div><div class="card"><div class="score">{{s?.open}}</div><p>Missions ouvertes</p></div></div></section>`}) class AdminDash{s:any;constructor(api:Api){api.stats().subscribe(s=>this.s=s)}}
@Component({standalone:true,imports:[CommonModule,FormsModule],template:`<section class="content"><h1>Gestion missions</h1><table class="table"><tr><th>Titre</th><th>Budget</th><th>Statut</th><th>Action</th></tr><tr *ngFor="let m of missions"><td>{{m.title}}</td><td>{{m.budget}}</td><td><select [(ngModel)]="m.status" (change)="update(m)"><option>open</option><option>assigned</option><option>in_progress</option><option>completed</option></select></td><td><button class="btn light" (click)="adminDelete(m.id)">Supprimer</button></td></tr></table></section>`}) class AdminMissions{missions:Mission[]=[];constructor(private api:Api){this.load()}load(){this.api.missions().subscribe(m=>this.missions=m)}update(m:Mission){this.api.updateMission(m.id,m).subscribe()}adminDelete(id:string){this.api.deleteMission(id,'admin@system.local').subscribe(()=>this.load())}}
@Component({standalone:true,imports:[CommonModule,FormsModule],template:`<section class="content"><h1>IA Matching avancé</h1><select [(ngModel)]="selected"><option *ngFor="let m of missions" [value]="m.id">{{m.title}}</option></select> <button class="btn" (click)="run()">Lancer matching</button><div class="grid"><div class="card" *ngFor="let r of results"><h3>{{r.developer.name}}</h3><div class="score">{{r.score}}%</div><p>{{r.explanation}}</p><span class="pill" *ngFor="let x of r.reasons">{{x}}</span></div></div></section>`}) class AdminAI{missions:Mission[]=[];selected='';results:any[]=[];constructor(private api:Api){api.missions().subscribe(m=>{this.missions=m;this.selected=m[0]?.id||''})}run(){this.api.match(this.selected).subscribe(r=>this.results=r)}}
const routes:Routes=[{path:'',component:PublicLayout,children:[{path:'',component:Home},{path:'missions',component:Missions},{path:'missions/:id',component:MissionDetail},{path:'publier',component:Publish},{path:'developers',component:Developers},{path:'assistant',component:AssistantAI}]},{path:'admin',component:AdminLayout,children:[{path:'',component:AdminDash},{path:'missions',component:AdminMissions},{path:'developers',component:Developers},{path:'ai',component:AdminAI}]}];
bootstrapApplication(Root,{providers:[provideHttpClient(),provideRouter(routes)]}).catch(err=>console.error(err));
